### PR TITLE
fix: adapt query to reference.

### PR DESCRIPTION
**Pull request by ahmetoz**

### CODE REVIEW

**Comment by lojzatran** [comment]
Do you want to add a test for it?

**Comment by butenkor** [comment]
Should not we also check if error is also 500 here: https://github.com/commercetools/commercetools-subscriptions/blob/da33405fe8733a7ebad1cf01e9660a9f66604884/src/create-subscription-orders.js#L194 ?

**Comment by lojzatran** [comment]
> Should not we also check if error is also 500 here:
> 
> https://github.com/commercetools/commercetools-subscriptions/blob/da33405fe8733a7ebad1cf01e9660a9f66604884/src/create-subscription-orders.js#L194
> 
> ?

https://github.com/commercetools/commercetools-subscriptions/pull/15/commits/d732cadf1d42bb2d540f5bd81f493624361f0fba

**Review by lojzatran — APPROVED** [review]

**Comment by lojzatran** [comment]
> Do you want to add a test for it?

I will add a test later in a different PR as we need to deploy this fix now.

**Pull request merged**
